export { Core } from './core/Core'
export { Curve } from './controllers/Curve'
export { FromTo } from './controllers/FromTo'
export { DEFAULTS } from './core/defaults'
export { easings } from './behaviors/easings'
export { EVENTS } from './core/events'
export { modes } from './behaviors/modes'
export { Manager, GlobalManager } from './core/Manager'
export { Loop } from './core/Loop'
export { play } from './core/play'
